version: "3"
services:
  jd_scripts_1: #自定义覆盖默认
    image: abclouds/jd_scripts
    restart: always
    container_name: jd_scripts1
    tty: true
    volumes:
      - ./logs1:/scripts/logs
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJgmpHdADB2Yr0Exzo2YFg8Bd7MZORuGZ5HmE272wWthj0mdUMOq5_-rzoINLQVR03vsIsOobw;pt_pin=jd_6b0945a180138;
      - TG_BOT_TOKEN=
      - TG_USER_ID=
      - CUSTOM_LIST_FILE=my_crontab_list.sh
      - CUSTOM_LIST_MERGE_TYPE=overwrite
      - TZ=Asia/Shanghai
        - LANG=en_US.UTF-8

  jd_scripts_2: #自定义覆盖默认
    image: abclouds/jd_scripts
    restart: always
    container_name: jd_scripts2
    tty: true
    volumes:
      - ./logs2:/scripts/logs
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJglTm9ADCwxZiv4ow-mX_fwi45IoZ1pKlp2qGIvbaGaqpn16F-48sM-OSv3eolyVuK8r9jexM;pt_pin=jd_49769225b01ed;
      - TG_BOT_TOKEN=
      - TG_USER_ID=
      - CUSTOM_LIST_FILE=my_crontab_list.sh
      - CUSTOM_LIST_MERGE_TYPE=overwrite
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

  jd_scripts_3: #自定义覆盖默认
    image: abclouds/jd_scripts
    restart: always
    container_name: jd_scripts3
    tty: true
    volumes:
      - ./logs3:/scripts/logs
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJglTo4AEAeYZwGFkrqwz-h3URz3ti8h_2M_yjBV7uvPZTXy09OTolyibC-DL9QTk4i1243p2zCgL3WiG8lAKhL85_JDtCu;pt_pin=%E5%8F%AB%E4%BB%80%E4%B9%88%E5%A5%BD%E5%91%A28370;
      - TG_BOT_TOKEN=
      - TG_USER_ID=
      - CUSTOM_LIST_FILE=my_crontab_list.sh
      - CUSTOM_LIST_MERGE_TYPE=overwrite
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

  jd_scripts_4: #自定义覆盖默认
    image: abclouds/jd_scripts
    restart: always
    container_name: jd_scripts4
    tty: true
    volumes:
      - ./logs4:/scripts/logs
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJgshWaADChz0BX53hyoBZWune6UKlpWT8HSE9rGJMLfn5iPi2RHwJ37utiyZqO4-3WmSpq0gU;pt_pin=candyclouds;
      - TG_BOT_TOKEN=
      - TG_USER_ID=
      - CUSTOM_LIST_FILE=my_crontab_list.sh
      - CUSTOM_LIST_MERGE_TYPE=overwrite
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
